# Generated by Django 3.1.7 on 2021-04-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=50, unique=True, verbose_name='Category Title')),
                ('category_description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('short_description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Short Description')),
                ('long_description', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Long Description')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Price')),
                ('is_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_title', models.CharField(max_length=50, unique=True, verbose_name='Sub-Category Title')),
                ('subcategory_description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
